# Generated by Django 3.2.6 on 2022-05-10 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('department', models.CharField(max_length=100, null=True)),
                ('institute', models.CharField(max_length=100, null=True)),
                ('target', models.CharField(blank=True, max_length=100)),
                ('duration', models.CharField(blank=True, max_length=100)),
                ('type', models.CharField(max_length=100, null=True)),
                ('stage', models.CharField(max_length=100, null=True)),
                ('scope', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'research',
            },
        ),
    ]
