# Generated by Django 3.2.6 on 2022-06-03 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_auto_20220510_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='is_updated',
            field=models.BooleanField(default=False),
        ),
    ]
