# Generated by Django 3.2.6 on 2022-06-03 18:28

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_auto_20220510_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='created_at',
            field=core.models.NoMillisecDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='research',
            name='updated_at',
            field=core.models.NoMillisecDateTimeField(auto_now=True),
        ),
    ]
