# Generated by Django 3.2.6 on 2022-05-11 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('APPLY_ENTP_NAME', models.CharField(default='', max_length=500, null=True, verbose_name='신청자')),
                ('APPROVAL_TIME', models.DateTimeField(default='', max_length=100, null=True, verbose_name='승인일')),
                ('LAB_NAME', models.CharField(default='', max_length=2000, null=True, verbose_name='실시기관명')),
                ('GOODS_NAME', models.CharField(default='', max_length=1000, null=True, verbose_name='제품명')),
                ('CLINIC_EXAM_TITLE', models.CharField(default='', max_length=2000, null=True, verbose_name='시험제목')),
                ('CLINIC_STEP_NAME', models.CharField(default='', max_length=500, null=True, verbose_name='단계')),
            ],
            options={
                'db_table': 'paper',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TotalNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('totalCount', models.IntegerField(verbose_name='마지막으로 기록된 전체 결과 수')),
            ],
            options={
                'db_table': 'total_number',
            },
        ),
    ]
