# Generated by Django 3.2.6 on 2022-06-03 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='is_updated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='totalnumber',
            name='is_updated',
            field=models.BooleanField(default=False),
        ),
    ]
